spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.211.55.3:1521:xe
    username: SOMANG
    password: SOMANG

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug